# Generated by Django 5.1.4 on 2026-06-19 06:36

import utils.go_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeassignment',
            name='go_file',
            field=models.FileField(blank=True, null=True, upload_to='go/committee/', validators=[utils.go_files.validate_go_file]),
        ),
    ]
