# Generated by Django 5.2.1 on 2026-09-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_committeeassignment_go_file'),
        ('master', '0015_subcommittee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeeassignment',
            options={'ordering': ['committee__name_bn', 'sub_committee__name_bn']},
        ),
        migrations.AddField(
            model_name='committeeassignment',
            name='sub_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='master.subcommittee', verbose_name='উপ-কমিটি'),
        ),
    ]
