# Generated by Django 5.2.1 on 2026-08-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_noc_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designation_bn',
            field=models.CharField(blank=True, max_length=200, verbose_name='পদবি (বাংলায়)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='ছবি'),
        ),
    ]
