# Generated by Django 5.2.1 on 2026-05-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_specialroletype_vaccinename'),
        ('mp', '0002_award_bankaccount_covidvaccination_and_more'),
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('go_number', models.CharField(blank=True, max_length=100)),
                ('go_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks_bn', models.TextField(blank=True)),
                ('remarks_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minister_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='master.ministertype')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='master.ministry')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_assignments', to='mp.mp')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ministry_assignments', to='parliament.parliament')),
            ],
            options={
                'ordering': ['minister_type__ordering', 'ministry__name_bn'],
            },
        ),
    ]
