# Generated by Django 5.2.1 on 2026-05-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mp', '0002_award_bankaccount_covidvaccination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentOfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('building_bn', models.CharField(blank=True, max_length=200)),
                ('building_en', models.CharField(blank=True, max_length=200)),
                ('address_bn', models.CharField(default='জাতীয় সংসদ ভবন, শের-ই-বাংলা নগর, ঢাকা-১২০৭', max_length=500)),
                ('address_en', models.CharField(default='National Parliament House, Sher-e-Bangla Nagar, Dhaka-1207', max_length=500)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('secretary_name_bn', models.CharField(blank=True, max_length=200)),
                ('secretary_name_en', models.CharField(blank=True, max_length=200)),
                ('secretary_mobile', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_address', to='mp.mp')),
            ],
        ),
    ]
