# Generated by Django 5.1.4 on 2026-06-19 06:36

import utils.go_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionassignment',
            name='nomination_date',
        ),
        migrations.AddField(
            model_name='institutionassignment',
            name='go_file',
            field=models.FileField(blank=True, null=True, upload_to='go/institution/', validators=[utils.go_files.validate_go_file]),
        ),
        migrations.AddField(
            model_name='institutionassignment',
            name='nominated_by',
            field=models.CharField(blank=True, choices=[('pm', 'প্রধানমন্ত্রী / Prime Minister'), ('speaker', 'স্পিকার / Speaker')], max_length=10),
        ),
    ]
