# Generated by Django 5.2.1 on 2026-05-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_specialroletype_vaccinename'),
        ('mp', '0001_initial'),
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=300, verbose_name='পুরস্কারের নাম (বাংলায়)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Award Name')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='সাল')),
                ('awarded_by_bn', models.CharField(blank=True, max_length=300, verbose_name='প্রদানকারী সংস্থা (বাংলায়)')),
                ('awarded_by_en', models.CharField(blank=True, max_length=300, verbose_name='Awarded By')),
                ('ordering', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='mp.mp')),
            ],
            options={
                'verbose_name': 'পুরস্কার',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='হিসাব নম্বর')),
                ('bank_name_bn', models.CharField(max_length=200, verbose_name='ব্যাংকের নাম (বাংলায়)')),
                ('bank_name_en', models.CharField(blank=True, max_length=200, verbose_name='Bank Name')),
                ('branch_name_bn', models.CharField(blank=True, max_length=200, verbose_name='শাখার নাম (বাংলায়)')),
                ('branch_name_en', models.CharField(blank=True, max_length=200, verbose_name='Branch Name')),
                ('routing_number', models.CharField(blank=True, max_length=30, verbose_name='রাউটিং নম্বর')),
                ('account_type', models.CharField(choices=[('savings', 'সঞ্চয়ী (Savings)'), ('current', 'চলতি (Current)'), ('other', 'অন্যান্য (Other)')], default='savings', max_length=20, verbose_name='হিসাবের ধরন')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='mp.mp')),
            ],
            options={
                'verbose_name': 'ব্যাংক হিসাব',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CovidVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.IntegerField(verbose_name='ডোজ নম্বর')),
                ('date', models.DateField(blank=True, null=True, verbose_name='তারিখ')),
                ('center_name', models.CharField(blank=True, max_length=300, verbose_name='টিকা কেন্দ্র')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='সার্টিফিকেট নম্বর')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid_vaccinations', to='mp.mp')),
                ('vaccine_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.vaccinename', verbose_name='টিকার নাম')),
            ],
            options={
                'verbose_name': 'কোভিড টিকা',
                'ordering': ['dose_number'],
            },
        ),
        migrations.CreateModel(
            name='ForeignLanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.foreignlanguage', verbose_name='ভাষা')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_skills', to='mp.mp')),
                ('proficiency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.proficiencylevel', verbose_name='দক্ষতার মাত্রা')),
            ],
            options={
                'verbose_name': 'বিদেশি ভাষার দক্ষতা',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=300, verbose_name='সংগঠনের নাম (বাংলায়)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Organization Name')),
                ('role_bn', models.CharField(blank=True, max_length=200, verbose_name='ভূমিকা (বাংলায়)')),
                ('role_en', models.CharField(blank=True, max_length=200, verbose_name='Role')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='শুরুর তারিখ')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='শেষ তারিখ')),
                ('ordering', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='mp.mp')),
            ],
            options={
                'verbose_name': 'সংগঠন',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreviousParliamentaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_name_bn', models.CharField(blank=True, max_length=200, verbose_name='সংসদের নাম (বাংলায়)')),
                ('assembly_name_en', models.CharField(blank=True, max_length=200, verbose_name='Assembly Name')),
                ('constituency_bn', models.CharField(blank=True, max_length=300, verbose_name='নির্বাচনী এলাকা (বাংলায়)')),
                ('constituency_en', models.CharField(blank=True, max_length=300, verbose_name='Constituency')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='শুরুর তারিখ')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='শেষ তারিখ')),
                ('remarks_bn', models.CharField(blank=True, max_length=500, verbose_name='মন্তব্য (বাংলায়)')),
                ('remarks_en', models.CharField(blank=True, max_length=500, verbose_name='Remarks')),
                ('ordering', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_histories', to='mp.mp')),
            ],
            options={
                'verbose_name': 'পূর্ববর্তী সংসদ ইতিহাস',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(max_length=300, verbose_name='শিরোনাম (বাংলায়)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (English)')),
                ('pub_year', models.IntegerField(blank=True, null=True, verbose_name='প্রকাশের সাল')),
                ('publisher_bn', models.CharField(blank=True, max_length=300, verbose_name='প্রকাশক (বাংলায়)')),
                ('publisher_en', models.CharField(blank=True, max_length=300, verbose_name='Publisher')),
                ('pub_type', models.CharField(choices=[('book', 'বই (Book)'), ('article', 'প্রবন্ধ (Article)'), ('research', 'গবেষণাপত্র (Research)'), ('other', 'অন্যান্য (Other)')], default='book', max_length=20, verbose_name='ধরন')),
                ('ordering', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='mp.mp')),
            ],
            options={
                'verbose_name': 'প্রকাশনা',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_bn', models.TextField(blank=True, verbose_name='সমাজ সেবা (বাংলায়)')),
                ('description_en', models.TextField(blank=True, verbose_name='Social Service (English)')),
                ('mp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_service', to='mp.mp')),
            ],
            options={
                'verbose_name': 'সমাজ সেবা',
            },
        ),
        migrations.CreateModel(
            name='SpecialPositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='শুরুর তারিখ')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='শেষ তারিখ')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_positions', to='mp.mp')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parliament.parliament', verbose_name='সংসদ')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.specialroletype', verbose_name='পদের নাম')),
            ],
            options={
                'verbose_name': 'বিশেষ পদ',
                'ordering': ['from_date'],
            },
        ),
    ]
