# Generated by Django 5.2.1 on 2026-07-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0002_award_bankaccount_covidvaccination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ব্যক্তিগত ই-মেইল'),
        ),
        migrations.AddField(
            model_name='mp',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='mp_signatures/', verbose_name='স্বাক্ষর'),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='দাপ্তরিক ই-মেইল'),
        ),
    ]
