# Generated by Django 5.2.1 on 2026-07-02 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0003_address_personal_email_mp_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MPSyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('field', 'Field value differs'), ('remove', 'Row exists here but not in API')], default='field', max_length=10)),
                ('target', models.CharField(choices=[('mp', 'MP'), ('election', 'Election'), ('address', 'Contact'), ('bank', 'Bank'), ('spouse', 'Spouse'), ('child', 'Child')], max_length=10)),
                ('attr', models.CharField(blank=True, help_text='Model attribute to set (field kind)', max_length=50)),
                ('field_key', models.CharField(help_text='Stable key within (mp, target), e.g. name_bn or bank.<acct>', max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('value_type', models.CharField(blank=True, max_length=10)),
                ('system_value', models.TextField(blank=True)),
                ('api_value', models.TextField(blank=True)),
                ('api_ref', models.TextField(blank=True, help_text='Apply payload: fk pk / scalar / iso-date / int, or the row pk to delete (remove kind)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('resolution', models.CharField(blank=True, choices=[('', '—'), ('system', 'Kept system value'), ('api', 'Applied API value')], default='', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflicts', to='mp.mp')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_conflicts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'সিঙ্ক দ্বন্দ্ব',
                'ordering': ['mp__mp_id', 'target', 'field_key'],
                'unique_together': {('mp', 'target', 'field_key')},
            },
        ),
    ]
