# Generated by Django 5.2.1 on 2026-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0006_mp_self_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='education',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='mp',
            name='is_self_educated',
            field=models.BooleanField(default=False, verbose_name='স্ব-শিক্ষিত'),
        ),
    ]
