# Generated by Django 5.2.1 on 2026-08-30 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_seed_result_masters'),
        ('mp', '0011_mp_nationality_bilingual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalForeignTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='যাত্রার তারিখ')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='প্রত্যাবর্তনের তারিখ')),
                ('note_bn', models.TextField(blank=True, verbose_name='মন্তব্য (বাংলায়)')),
                ('note_en', models.TextField(blank=True, verbose_name='Remarks (English)')),
                ('ordering', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_visits', to='master.country', verbose_name='দেশ')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_travels', to='mp.mp')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_visits', to='master.travelpurpose', verbose_name='উদ্দেশ্য')),
            ],
            options={
                'verbose_name': 'ব্যক্তিগত বিদেশ ভ্রমণ',
                'ordering': [models.OrderBy(models.F('from_date'), descending=True, nulls_last=True), 'ordering', 'id'],
            },
        ),
    ]
