# Generated by Django 5.2.1 on 2026-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0013_education_class_result_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalforeigntravel',
            options={'ordering': [models.OrderBy(models.F('sort_year'), descending=True, nulls_last=True), models.OrderBy(models.F('from_date'), descending=True, nulls_last=True), 'ordering', 'id'], 'verbose_name': 'ব্যক্তিগত বিদেশ ভ্রমণ'},
        ),
        migrations.AddField(
            model_name='personalforeigntravel',
            name='sort_year',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='personalforeigntravel',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='সন'),
        ),
    ]
