# Generated by Django 5.2.1 on 2026-09-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0016_address_post_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialpositionhistory',
            options={'ordering': ['role__ordering', 'role__name_bn', '-from_date'], 'verbose_name': 'সংসদীয় পদ'},
        ),
        migrations.AddField(
            model_name='specialpositionhistory',
            name='go_date',
            field=models.DateField(blank=True, null=True, verbose_name='GO/প্রজ্ঞাপনের তারিখ'),
        ),
        migrations.AddField(
            model_name='specialpositionhistory',
            name='go_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='GO/প্রজ্ঞাপন নং'),
        ),
        migrations.AddField(
            model_name='specialpositionhistory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='বর্তমানে বহাল'),
        ),
        migrations.AddField(
            model_name='specialpositionhistory',
            name='remarks_bn',
            field=models.TextField(blank=True, verbose_name='মন্তব্য (বাংলায়)'),
        ),
        migrations.AddField(
            model_name='specialpositionhistory',
            name='remarks_en',
            field=models.TextField(blank=True, verbose_name='Remarks (English)'),
        ),
    ]
