# Generated by Django 5.2.1 on 2026-09-21 06:30

import django.db.models.deletion
import utils.prp_files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0017_alter_specialpositionhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='prp_form_file',
            field=models.FileField(blank=True, max_length=255, storage=utils.prp_files.prp_storage, upload_to=utils.prp_files.prp_form_upload_to, validators=[utils.prp_files.validate_prp_file], verbose_name='PRP ফরম (স্ক্যান কপি)'),
        ),
        migrations.AddField(
            model_name='mp',
            name='prp_form_original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='আপলোডকৃত ফাইলের নাম'),
        ),
        migrations.AddField(
            model_name='mp',
            name='prp_form_submitted',
            field=models.BooleanField(default=False, verbose_name='PRP ফরম জমা দিয়েছেন (হার্ডকপি)'),
        ),
        migrations.AddField(
            model_name='mp',
            name='prp_form_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='আপলোডের সময়'),
        ),
        migrations.AddField(
            model_name='mp',
            name='prp_form_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prp_forms_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='আপলোডকারী'),
        ),
    ]
