# Generated by Django 5.1.4 on 2026-06-19 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_officerdesignation'),
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constituencies', to='master.district'),
        ),
    ]
