import json, sys, os
sys.stdout.reconfigure(encoding='utf-8')

countries = [
    ('Bangladesh', 'বাংলাদেশ'),
    ('Afghanistan', 'আফগানিস্তান'),
    ('Albania', 'আলবেনিয়া'),
    ('Algeria', 'আলজেরিয়া'),
    ('Andorra', 'আন্দোরা'),
    ('Angola', 'অ্যাঙ্গোলা'),
    ('Antigua and Barbuda', 'অ্যান্টিগুয়া ও বার্বুডা'),
    ('Argentina', 'আর্জেন্টিনা'),
    ('Armenia', 'আর্মেনিয়া'),
    ('Australia', 'অস্ট্রেলিয়া'),
    ('Austria', 'অস্ট্রিয়া'),
    ('Azerbaijan', 'আজারবাইজান'),
    ('Bahamas', 'বাহামাস'),
    ('Bahrain', 'বাহরাইন'),
    ('Barbados', 'বার্বাডোস'),
    ('Belarus', 'বেলারুশ'),
    ('Belgium', 'বেলজিয়াম'),
    ('Belize', 'বেলিজ'),
    ('Benin', 'বেনিন'),
    ('Bhutan', 'ভুটান'),
    ('Bolivia', 'বলিভিয়া'),
    ('Bosnia and Herzegovina', 'বসনিয়া ও হার্জেগোভিনা'),
    ('Botswana', 'বোতসোয়ানা'),
    ('Brazil', 'ব্রাজিল'),
    ('Brunei', 'ব্রুনাই'),
    ('Bulgaria', 'বুলগেরিয়া'),
    ('Burkina Faso', 'বুর্কিনা ফাসো'),
    ('Burundi', 'বুরুন্ডি'),
    ('Cabo Verde', 'কেপ ভার্দে'),
    ('Cambodia', 'কম্বোডিয়া'),
    ('Cameroon', 'ক্যামেরুন'),
    ('Canada', 'কানাডা'),
    ('Central African Republic', 'মধ্য আফ্রিকান প্রজাতন্ত্র'),
    ('Chad', 'চাদ'),
    ('Chile', 'চিলি'),
    ('China', 'চীন'),
    ('Colombia', 'কলম্বিয়া'),
    ('Comoros', 'কমোরোস'),
    ('Congo (Republic)', 'কঙ্গো প্রজাতন্ত্র'),
    ('Congo (Democratic Republic)', 'গণতান্ত্রিক কঙ্গো প্রজাতন্ত্র'),
    ('Costa Rica', 'কোস্টারিকা'),
    ('Croatia', 'ক্রোয়েশিয়া'),
    ('Cuba', 'কিউবা'),
    ('Cyprus', 'সাইপ্রাস'),
    ('Czech Republic', 'চেক প্রজাতন্ত্র'),
    ('Denmark', 'ডেনমার্ক'),
    ('Djibouti', 'জিবুতি'),
    ('Dominica', 'ডমিনিকা'),
    ('Dominican Republic', 'ডমিনিকান প্রজাতন্ত্র'),
    ('Ecuador', 'ইকুয়েডর'),
    ('Egypt', 'মিশর'),
    ('El Salvador', 'এল সালভাদর'),
    ('Equatorial Guinea', 'বিষুবীয় গিনি'),
    ('Eritrea', 'ইরিত্রিয়া'),
    ('Estonia', 'এস্তোনিয়া'),
    ('Eswatini', 'ইসওয়াতিনি'),
    ('Ethiopia', 'ইথিওপিয়া'),
    ('Fiji', 'ফিজি'),
    ('Finland', 'ফিনল্যান্ড'),
    ('France', 'ফ্রান্স'),
    ('Gabon', 'গ্যাবন'),
    ('Gambia', 'গাম্বিয়া'),
    ('Georgia', 'জর্জিয়া'),
    ('Germany', 'জার্মানি'),
    ('Ghana', 'ঘানা'),
    ('Greece', 'গ্রিস'),
    ('Grenada', 'গ্রেনাডা'),
    ('Guatemala', 'গুয়াতেমালা'),
    ('Guinea', 'গিনি'),
    ('Guinea-Bissau', 'গিনি-বিসাউ'),
    ('Guyana', 'গায়ানা'),
    ('Haiti', 'হাইতি'),
    ('Honduras', 'হন্ডুরাস'),
    ('Hungary', 'হাঙ্গেরি'),
    ('Iceland', 'আইসল্যান্ড'),
    ('India', 'ভারত'),
    ('Indonesia', 'ইন্দোনেশিয়া'),
    ('Iran', 'ইরান'),
    ('Iraq', 'ইরাক'),
    ('Ireland', 'আয়ারল্যান্ড'),
    ('Israel', 'ইসরায়েল'),
    ('Italy', 'ইতালি'),
    ('Ivory Coast', 'আইভরি কোস্ট'),
    ('Jamaica', 'জামাইকা'),
    ('Japan', 'জাপান'),
    ('Jordan', 'জর্ডান'),
    ('Kazakhstan', 'কাজাখস্তান'),
    ('Kenya', 'কেনিয়া'),
    ('Kiribati', 'কিরিবাতি'),
    ('Kosovo', 'কসোভো'),
    ('Kuwait', 'কুয়েত'),
    ('Kyrgyzstan', 'কির্গিজস্তান'),
    ('Laos', 'লাওস'),
    ('Latvia', 'লাটভিয়া'),
    ('Lebanon', 'লেবানন'),
    ('Lesotho', 'লেসোথো'),
    ('Liberia', 'লাইবেরিয়া'),
    ('Libya', 'লিবিয়া'),
    ('Liechtenstein', 'লিশটেনস্টাইন'),
    ('Lithuania', 'লিথুয়ানিয়া'),
    ('Luxembourg', 'লুক্সেমবার্গ'),
    ('Madagascar', 'মাদাগাস্কার'),
    ('Malawi', 'মালাউই'),
    ('Malaysia', 'মালয়েশিয়া'),
    ('Maldives', 'মালদ্বীপ'),
    ('Mali', 'মালি'),
    ('Malta', 'মালটা'),
    ('Marshall Islands', 'মার্শাল দ্বীপপুঞ্জ'),
    ('Mauritania', 'মৌরিতানিয়া'),
    ('Mauritius', 'মরিশাস'),
    ('Mexico', 'মেক্সিকো'),
    ('Micronesia', 'মাইক্রোনেশিয়া'),
    ('Moldova', 'মলদোভা'),
    ('Monaco', 'মোনাকো'),
    ('Mongolia', 'মঙ্গোলিয়া'),
    ('Montenegro', 'মন্টেনেগ্রো'),
    ('Morocco', 'মরক্কো'),
    ('Mozambique', 'মোজাম্বিক'),
    ('Myanmar', 'মিয়ানমার'),
    ('Namibia', 'নামিবিয়া'),
    ('Nauru', 'নাউরু'),
    ('Nepal', 'নেপাল'),
    ('Netherlands', 'নেদারল্যান্ডস'),
    ('New Zealand', 'নিউজিল্যান্ড'),
    ('Nicaragua', 'নিকারাগুয়া'),
    ('Niger', 'নাইজার'),
    ('Nigeria', 'নাইজেরিয়া'),
    ('North Korea', 'উত্তর কোরিয়া'),
    ('North Macedonia', 'উত্তর মেসিডোনিয়া'),
    ('Norway', 'নরওয়ে'),
    ('Oman', 'ওমান'),
    ('Pakistan', 'পাকিস্তান'),
    ('Palau', 'পালাউ'),
    ('Palestine', 'ফিলিস্তিন'),
    ('Panama', 'পানামা'),
    ('Papua New Guinea', 'পাপুয়া নিউ গিনি'),
    ('Paraguay', 'প্যারাগুয়ে'),
    ('Peru', 'পেরু'),
    ('Philippines', 'ফিলিপাইন'),
    ('Poland', 'পোল্যান্ড'),
    ('Portugal', 'পর্তুগাল'),
    ('Qatar', 'কাতার'),
    ('Romania', 'রোমানিয়া'),
    ('Russia', 'রাশিয়া'),
    ('Rwanda', 'রুয়ান্ডা'),
    ('Saint Kitts and Nevis', 'সেন্ট কিটস ও নেভিস'),
    ('Saint Lucia', 'সেন্ট লুসিয়া'),
    ('Saint Vincent and the Grenadines', 'সেন্ট ভিনসেন্ট ও গ্রেনাডাইনস'),
    ('Samoa', 'সামোয়া'),
    ('San Marino', 'সান মারিনো'),
    ('Sao Tome and Principe', 'সাও তোমে ও প্রিন্সিপে'),
    ('Saudi Arabia', 'সৌদি আরব'),
    ('Senegal', 'সেনেগাল'),
    ('Serbia', 'সার্বিয়া'),
    ('Seychelles', 'সেশেলস'),
    ('Sierra Leone', 'সিয়েরা লিওন'),
    ('Singapore', 'সিঙ্গাপুর'),
    ('Slovakia', 'স্লোভাকিয়া'),
    ('Slovenia', 'স্লোভেনিয়া'),
    ('Solomon Islands', 'সলোমন দ্বীপপুঞ্জ'),
    ('Somalia', 'সোমালিয়া'),
    ('South Africa', 'দক্ষিণ আফ্রিকা'),
    ('South Korea', 'দক্ষিণ কোরিয়া'),
    ('South Sudan', 'দক্ষিণ সুদান'),
    ('Spain', 'স্পেন'),
    ('Sri Lanka', 'শ্রীলঙ্কা'),
    ('Sudan', 'সুদান'),
    ('Suriname', 'সুরিনাম'),
    ('Sweden', 'সুইডেন'),
    ('Switzerland', 'সুইজারল্যান্ড'),
    ('Syria', 'সিরিয়া'),
    ('Taiwan', 'তাইওয়ান'),
    ('Tajikistan', 'তাজিকিস্তান'),
    ('Tanzania', 'তানজানিয়া'),
    ('Thailand', 'থাইল্যান্ড'),
    ('Timor-Leste', 'তিমুর-লেস্তে'),
    ('Togo', 'টোগো'),
    ('Tonga', 'টোঙ্গা'),
    ('Trinidad and Tobago', 'ত্রিনিদাদ ও টোবাগো'),
    ('Tunisia', 'তিউনিসিয়া'),
    ('Turkey', 'তুরস্ক'),
    ('Turkmenistan', 'তুর্কমেনিস্তান'),
    ('Tuvalu', 'টুভালু'),
    ('Uganda', 'উগান্ডা'),
    ('Ukraine', 'ইউক্রেন'),
    ('United Arab Emirates', 'সংযুক্ত আরব আমিরাত'),
    ('United Kingdom', 'যুক্তরাজ্য'),
    ('United States', 'যুক্তরাষ্ট্র'),
    ('Uruguay', 'উরুগুয়ে'),
    ('Uzbekistan', 'উজবেকিস্তান'),
    ('Vanuatu', 'ভানুয়াতু'),
    ('Vatican City', 'ভ্যাটিকান সিটি'),
    ('Venezuela', 'ভেনিজুয়েলা'),
    ('Vietnam', 'ভিয়েতনাম'),
    ('Yemen', 'ইয়েমেন'),
    ('Zambia', 'জাম্বিয়া'),
    ('Zimbabwe', 'জিম্বাবুয়ে'),
]

fixtures = []
for idx, (name_en, name_bn) in enumerate(countries, start=1):
    fixtures.append({
        'model': 'master.country',
        'pk': idx,
        'fields': {
            'name_bn': name_bn,
            'name_en': name_en,
            'is_active': True,
            'ordering': idx,
        }
    })

out_path = os.path.join(os.path.dirname(__file__), '..', 'fixtures', 'initial', 'country_name_list.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(fixtures, f, ensure_ascii=False, indent=2)

print(f'country_name_list.json: {len(fixtures)} records')
print(f'First : {fixtures[0]["fields"]["name_en"]} / {fixtures[0]["fields"]["name_bn"]}')
print(f'Last  : {fixtures[-1]["fields"]["name_en"]} / {fixtures[-1]["fields"]["name_bn"]}')
