# Generated by Django 5.2.1 on 2026-05-20 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_specialroletype_vaccinename'),
        ('mp', '0002_award_bankaccount_covidvaccination_and_more'),
        ('parliament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_number', models.CharField(max_length=200)),
                ('go_date', models.DateField()),
                ('purpose_detail_bn', models.TextField(blank=True)),
                ('purpose_detail_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tours', to=settings.AUTH_USER_MODEL)),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_tours', to='parliament.parliament')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='master.travelpurpose')),
                ('tour_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='master.traveltype')),
            ],
            options={
                'ordering': ['-go_date'],
            },
        ),
        migrations.CreateModel(
            name='ForeignTourCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_visits', to='master.country')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='travel.foreigntour')),
            ],
            options={
                'ordering': ['ordering'],
                'unique_together': {('tour', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ForeignTourParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('remarks_bn', models.TextField(blank=True)),
                ('remarks_en', models.TextField(blank=True)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_participations', to='mp.mp')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='travel.foreigntour')),
            ],
            options={
                'ordering': ['mp__name_bn'],
                'unique_together': {('tour', 'mp')},
            },
        ),
    ]
