# Generated by Django 5.1.4 on 2026-06-19 06:36

import django.db.models.deletion
import utils.go_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_officerdesignation'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreigntourparticipant',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='foreigntourparticipant',
            name='return_date',
        ),
        migrations.AddField(
            model_name='foreigntour',
            name='go_file',
            field=models.FileField(blank=True, null=True, upload_to='go/travel/', validators=[utils.go_files.validate_go_file]),
        ),
        migrations.AddField(
            model_name='foreigntourcountry',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreigntourcountry',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ForeignTourOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('remarks_bn', models.TextField(blank=True)),
                ('remarks_en', models.TextField(blank=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_officers', to='master.officerdesignation')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='travel.foreigntour')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
