# Generated by Django 4.2.7 on 2026-05-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_specialroletype_vaccinename'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionresult',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
