# Generated by Django 5.2.1 on 2026-07-24 14:03

from django.db import migrations, models


def merge_school_scopes(apps, schema_editor):
    """SSC/HSC/Diploma now share ONE group pool → collapse the old separate
    'secondary' and 'higher_sec' scopes into 'school'."""
    EducationGroup = apps.get_model('master', 'EducationGroup')
    EducationGroup.objects.filter(
        applicable_to__in=['secondary', 'higher_sec']
    ).update(applicable_to='school')


def split_school_scope(apps, schema_editor):
    """Reverse: best-effort restore — put shared 'school' groups back on the
    old 'secondary' scope (HSC-specific tagging is not recoverable)."""
    EducationGroup = apps.get_model('master', 'EducationGroup')
    EducationGroup.objects.filter(applicable_to='school').update(applicable_to='secondary')


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_seed_education_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroup',
            name='applicable_to',
            field=models.CharField(choices=[('school', 'School Level (SSC / HSC / Diploma)'), ('university', 'University Level (Graduation / Masters / PhD)'), ('all', 'All Levels')], default='all', max_length=20),
        ),
        migrations.RunPython(merge_school_scopes, split_school_scope),
    ]
