# Generated by Django 5.2.1 on 2026-09-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_seed_vaccine_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialroletype',
            name='is_unique_per_parliament',
            field=models.BooleanField(default=False, help_text='স্পিকার, ডেপুটি স্পিকার, চিফ হুইপ ইত্যাদির মতো একক পদ হলে টিক দিন। Tick for single-holder offices (Speaker, Chief Whip, …).', verbose_name='এক সংসদে একজন'),
        ),
    ]
