# Generated by Django 5.2.1 on 2026-09-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_seed_parliamentary_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=0)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_committees', to='master.standingcommittee', verbose_name='স্থায়ী কমিটি')),
            ],
            options={
                'ordering': ['committee__ordering', 'committee__name_bn', 'ordering', 'name_bn'],
            },
        ),
    ]
