# Generated by Django 5.2.1 on 2026-08-23 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mp', '0010_spouse_passport'),
        ('officer', '0001_initial'),
        ('travel', '0004_officer_roster_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NOCLetterhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_bn', models.CharField(default='বাংলাদেশ জাতীয় সংসদ সচিবালয়', max_length=200, verbose_name='প্রতিষ্ঠান (বাংলায়)')),
                ('org_en', models.CharField(default='BANGLADESH PARLIAMENT SECRETARIAT', max_length=200, verbose_name='Organisation (English)')),
                ('wing_bn', models.CharField(blank=True, default='আইপিএ এন্ড এস অনুবিভাগ', max_length=200, verbose_name='অনুবিভাগ (বাংলায়)')),
                ('wing_en', models.CharField(blank=True, default='IPA and S Wing', max_length=200, verbose_name='Wing (English)')),
                ('section_bn', models.CharField(blank=True, default='আইপিএ শাখা-২', max_length=200, verbose_name='শাখা (বাংলায়)')),
                ('section_en', models.CharField(blank=True, default='IPA Section-2', max_length=200, verbose_name='Section (English)')),
                ('address_bn', models.CharField(blank=True, default='সংসদ-ভবন, ঢাকা', max_length=200, verbose_name='ঠিকানা (বাংলায়)')),
                ('address_en', models.CharField(blank=True, default='PARLIAMENT HOUSE, DHAKA.', max_length=200, verbose_name='Address (English)')),
                ('website', models.CharField(blank=True, default='www.parliament.gov.bd', max_length=200, verbose_name='ওয়েবসাইট')),
                ('telephone', models.CharField(blank=True, default='9110140/8171426', max_length=100, verbose_name='টেলিফোন')),
                ('fax', models.CharField(blank=True, default='88-02-9119186/9113767', max_length=100, verbose_name='ফ্যাক্স')),
                ('email', models.CharField(blank=True, default='ipa2branch@gmail.com', max_length=200, verbose_name='ই-মেইল')),
                ('memo_prefix', models.CharField(default='11.00.0000.000.610.37.0002', max_length=200, verbose_name='স্মারক নম্বরের প্রথমাংশ')),
                ('speaker_title_bn', models.CharField(default='মাননীয় ভারপ্রাপ্ত স্পীকার', max_length=200, verbose_name='স্পীকারের পদবী (বাংলায়)')),
                ('speaker_title_en', models.CharField(default="Hon'ble Acting Speaker", max_length=200, verbose_name='Speaker title (English)')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NOC লেটারহেড',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NOCTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=200, verbose_name='নাম (বাংলায়)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (English)')),
                ('language', models.CharField(choices=[('bn', 'বাংলা পত্র / Bangla forwarding letter'), ('en', 'ইংরেজি সনদ / English certificate')], default='en', max_length=2, verbose_name='ভাষা')),
                ('body_html', models.TextField(verbose_name='দলিলের বিন্যাস (HTML)')),
                ('is_default', models.BooleanField(default=False, verbose_name='ডিফল্ট')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NOC টেমপ্লেট',
                'ordering': ['language', 'ordering', 'name_bn'],
            },
        ),
        migrations.CreateModel(
            name='NOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('bn', 'বাংলা পত্র / Bangla forwarding letter'), ('en', 'ইংরেজি সনদ / English certificate')], default='en', max_length=2, verbose_name='ভাষা')),
                ('memo_no', models.CharField(max_length=200, verbose_name='স্মারক নম্বর')),
                ('serial_no', models.IntegerField(blank=True, null=True, verbose_name='ক্রমিক')),
                ('issue_date', models.DateField(verbose_name='তারিখ')),
                ('signatory_name_bn', models.CharField(blank=True, max_length=200)),
                ('signatory_name_en', models.CharField(blank=True, max_length=200)),
                ('signatory_designation_bn', models.CharField(blank=True, max_length=200)),
                ('signatory_designation_en', models.CharField(blank=True, max_length=200)),
                ('signatory_phone', models.CharField(blank=True, max_length=50)),
                ('signatory_mobile', models.CharField(blank=True, max_length=50)),
                ('signatory_email', models.CharField(blank=True, max_length=200)),
                ('body_html', models.TextField(blank=True, verbose_name='দলিল')),
                ('status', models.CharField(choices=[('draft', 'খসড়া / Draft'), ('final', 'চূড়ান্ত / Final')], default='draft', max_length=10, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nocs', to=settings.AUTH_USER_MODEL)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nocs', to='mp.mp', verbose_name='সংসদ সদস্য')),
                ('signatory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_nocs', to='officer.officer', verbose_name='স্বাক্ষরকারী')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nocs', to='mp.spouse', verbose_name='সঙ্গী স্বামী/স্ত্রী')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nocs', to='travel.foreigntour', verbose_name='বিদেশ ভ্রমণ GO')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_nocs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='noc.noctemplate', verbose_name='টেমপ্লেট')),
            ],
            options={
                'verbose_name': 'অনাপত্তি সনদ (NOC)',
                'ordering': ['-issue_date', '-id'],
                'indexes': [models.Index(fields=['memo_no'], name='noc_noc_memo_no_e91406_idx'), models.Index(fields=['issue_date'], name='noc_noc_issue_d_9b1b32_idx')],
            },
        ),
    ]
